config/routes.rb
Rails.application.routes.draw do

  resources :moods do
    resources :cocktails
  end

resources :cocktails do
    	resources :ingredients
    end

  root "moods#index"
end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  belongs_to :mood
  has_many :ingredients
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	belongs_to :cocktail
end

app/models/mood.rb
class Mood < ActiveRecord::Base
	has_many :cocktails
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
	before_action :set_mood, only: [:create, :destroy]
	before_action :set_cocktail, only: :show


	def create
		@cocktail = @mood.cocktails.create(cocktail_params)

		redirect_to @mood 
	end

	def destroy
		@cocktail = @mood.cocktails.find(params[:id])
		if @cocktail.destroy
			flash[:success] = "Cocktail was removed."
		else
			flash[:error] = "Cocktail could not be removed."
		end
		redirect_to @mood
	end

	def show
		@mood = Mood.find(params[:mood_id])
	end

private

	def set_mood
		@mood = Mood.find(params[:mood_id])
	end

	def set_cocktail
		@cocktail = Cocktail.find(params[:id])
	end

	def cocktail_params
		params[:cocktail].permit(:drink_name)
	end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_cocktail
  

  def create
    @ingredient = @cocktail.ingredients.create(ingredient_params)
  	if @ingredient.save
  		flash[:notice] = "Ingredient Saved"
  		redirect_to @cocktail
  	else
  		render :new
  	end
  end

  def show
  	@ingredient = Ingredient.find(params[:id])
  end

  def edit
  	@ingredient = Ingredient.find(params[:id])
  end

  def update
  	@ingredient = Ingredient.find(params[:id])
  	if @ingredient.update (ingredient_params)
  		flash[:notice] = "Ingredient Updated"
  	else
  		render :edit
  	end
  end

  def destroy
    @ingredient = @cocktail.ingredients.find(params[:id])
    if @ingredient.destroy
      flash[:notice] = "Ingredient Deleted"
    else
      flash[:notice] = "Ingredient Couldn't be Deleted"
    end
    redirect_to @cocktail
  end

  private
    def set_cocktail
      @cocktail = Cocktail.find(params[:cocktail_id])
    end

    def ingredient_params
    	params[:ingredient].permit(:ing_item, :unit, :amount, :cocktail_id)
    end
 
  
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  before_action :set_mood, only: [:show, :edit, :update, :destroy]

  # GET /moods
  # GET /moods.json
  def index
    @moods = Mood.all
  end

  # GET /moods/1
  # GET /moods/1.json
  def show
    @mood = Mood.find(params[:id])
  end

  # GET /moods/new
  def new
    @mood = Mood.new
  end

  # GET /moods/1/edit
  def edit
  end

  # POST /moods
  # POST /moods.json
  def create
    @mood = Mood.new(mood_params)

    respond_to do |format|
      if @mood.save
        format.html { redirect_to @mood, notice: 'Mood was successfully created.' }
        format.json { render :show, status: :created, location: @mood }
      else
        format.html { render :new }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moods/1
  # PATCH/PUT /moods/1.json
  def update
    respond_to do |format|
      if @mood.update(mood_params)
        format.html { redirect_to @mood, notice: 'Mood was successfully updated.' }
        format.json { render :show, status: :ok, location: @mood }
      else
        format.html { render :edit }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moods/1
  # DELETE /moods/1.json
  def destroy
    @mood.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Mood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mood
      @mood = Mood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mood_params
      params.require(:mood).permit(:mood, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/views/cocktails/_cocktail.html.erb
<div class="row clearfix">
<div class="cocktail">
<p><%= link_to cocktail.drink_name, mood_cocktail_path(@mood, cocktail.id)%></p>
</div>
<div class="trash">
<%= link_to mood_cocktail_path(@mood, cocktail.id), method: :delete, data: {confirm: "Are you sure?"} do %>
<i class= "fa fa-trash"></i>
<% end %>
</div>
</div>

app/views/cocktails/_form.html.erb
<%= form_for( [@mood, @mood.cocktails.build]) do |f| %>
<%= f.text_field :drink_name, placeholder: "Name of cocktail" %>
<%= f.submit %>
<% end %>

app/views/cocktails/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="mood_title"><%= @cocktail.drink_name %></h1>


<div id="ingredients_wrapper">
	<%= render @cocktail.ingredients %>
	 <div id="form">
		<%= render "ingredients/form" %>
	</div>
</div>
<div class="links">
<%= link_to 'Edit', edit_cocktail_path(@cocktail) %> |
<%= link_to 'Delete', cocktail_path(@cocktail), method: :delete, data: {confirm: "Are you sure?"} %> |
<%= link_to 'Back', mood_path(@mood) %> 

</div>

app/views/ingredients/_form.html.erb
<%= form_for( [@cocktail, @cocktail.ingredients.build]) do |f| %>
<%= f.text_field :amount, placeholder: "1.5" %>
<%= f.text_field :unit, placeholder: "oz" %>
<%= f.text_field :ing_item, placeholder: "Vodka" %>
<br>
<%= f.submit %>

<% end %>

app/views/ingredients/_ingredient.html.erb
<div class="row clearfix">
<div class="ingredient">
<p><%= (ingredient.amount).to_s + " " + (ingredient.unit).to_s + " of " + (ingredient.ing_item).to_s %></p>
</div>
<div class="trash">
<%= link_to cocktail_ingredient_path(@cocktail, ingredient.id), method: :delete, data: {confirm: "Are you sure?"} do %>
<i class= "fa fa-trash"></i>
<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moodtails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>
<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/moods/_form.html.erb
<%= form_for(@mood) do |f| %>
  <% if @mood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mood.errors.count, "error") %> prohibited this mood from being saved:</h2>

      <ul>
      <% @mood.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mood %><br>
    <%= f.text_field :mood %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/moods/edit.html.erb
<h1 class="mood_title">Edit Mood</h1>
<div class="forms">
<%= render 'form' %>
</div>

<div class="links">
<%= link_to 'Cancel', moods_path %>
</div>

app/views/moods/index.html.erb
<% @moods.each do |mood| %>
<div class="index_row clearfix">
  <h2 class="mood_title"><%= link_to mood.mood, mood %></h2>
  <p class="mood_sub_title"> <%= mood.description%></p>
</div>
<% end %>

<div class="links">
  <%= link_to "New Mood", new_mood_path %>
</div>

app/views/moods/new.html.erb
<h1 class="mood_title">New Mood</h1>
<div class="forms">
<%= render 'form' %>
</div>

<div class="links">
<%= link_to 'Back', moods_path %>
</div>

app/views/moods/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="mood_title"><%= @mood.mood %></h2>

<p class="mood_sub_title"><%= @mood.description%></p>


<div id="cocktails_wrapper">
	<%= render @mood.cocktails %>
	<div id="form">
		<%= render "cocktails/form" %>
	</div>
</div>
<div class="links">
<%= link_to 'Edit', edit_mood_path(@mood) %> |
<%= link_to 'Delete', mood_path(@mood), method: :delete, data: {confirm: "Are you sure?"} %> |
<%= link_to 'Back', moods_path %> 

</div>